// // // import { ArrowLeft, ArrowRight, Loader2, type LucideIcon } from "lucide-react"

// // // export type IconKeys = "spinner" | "arrowRight" | "arrowLeft"

// // // export const Icons: Record<IconKeys, LucideIcon> = {
// // //   spinner: Loader2,
// // //   arrowRight: ArrowRight,
// // //   arrowLeft: ArrowLeft,
// // // }

// // import {
// //   AlertTriangle,
// //   Building2,
// //   Plus,
// //   MessageSquare,
// //   Bell,
// //   Send,
// //   UserCheck,
// //   Tag,
// //   Calendar,
// //   Eye,
// //   Edit,
// //   Trash2,
// //   Clock,
// //   Shield,
// //   Activity,
// //   Stethoscope,
// //   User,
// //   Phone,
// //   Mail,
// //   Navigation,
// //   Timer,
// //   RefreshCw,
// //   CheckCircle,
// //   XCircle,
// //   Map,
// //   MapPin,
// //   ExternalLink,
// //   Megaphone,
// //   AtSign,
// //   Award,
// //   Home,
// //   ClipboardList,
// //   UserCog,
// //   Users,
// //   ChevronUp,
// //   PanelLeft,
// //   CircleUser,
// // } from "lucide-react"

// // export const Icons = {
// //   AlertTriangle,
// //   Building2,
// //   Plus,
// //   MessageSquare,
// //   Bell,
// //   Send,
// //   UserCheck,
// //   Tag,
// //   Calendar,
// //   Eye,
// //   Edit,
// //   Trash2,
// //   Clock,
// //   Shield,
// //   Activity,
// //   Stethoscope,
// //   User,
// //   Phone,
// //   Mail,
// //   Navigation,
// //   Timer,
// //   RefreshCw,
// //   CheckCircle,
// //   XCircle,
// //   Map,
// //   MapPin,
// //   ExternalLink,
// //   Megaphone,
// //   AtSign,
// //   Award,
// //   Home,
// //   ClipboardList,
// //   UserCog,
// //   Users,
// //   ChevronUp,
// //   PanelLeft,
// //   CircleUser,
// // }

// import {
//   AlertTriangle,
//   Building2,
//   Plus,
//   MessageSquare,
//   Bell,
//   Send,
//   UserCheck,
//   Tag,
//   Calendar,
//   Eye,
//   Edit,
//   Trash2,
//   Clock,
//   Shield,
//   Activity,
//   Stethoscope,
//   User,
//   Phone,
//   Mail,
//   Navigation,
//   Timer,
//   RefreshCw,
//   CheckCircle,
//   XCircle,
//   Map,
//   MapPin,
//   ExternalLink,
//   Megaphone,
//   AtSign,
//   Award,
//   Home,
//   ClipboardList,
//   UserCog,
//   Users,
//   ChevronUp,
//   PanelLeft,
//   CircleUser,
//   Loader2
// } from "lucide-react"

// export const Icons = {
//   AlertTriangle,
//    spinner: Loader2,
//   Building2,
//   Plus,
//   MessageSquare,
//   Bell,
//   Send,
//   UserCheck,
//   Tag,
//   Calendar,
//   Eye,
//   Edit,
//   Trash2,
//   Clock,
//   Shield,
//   Activity,
//   Stethoscope,
//   User,
//   Phone,
//   Mail,
//   Navigation,
//   Timer,
//   RefreshCw,
//   CheckCircle,
//   XCircle,
//   Map,
//   MapPin,
//   ExternalLink,
//   Megaphone,
//   AtSign,
//   Award,
//   Home,
//   ClipboardList,
//   UserCog,
//   Users,
//   ChevronUp,
//   PanelLeft,
//   CircleUser,
// }


import {
  AlertTriangle,
  Building2,
  Plus,
  MessageSquare,
  Bell,
  Send,
  UserCheck,
  Tag,
  Calendar,
  Eye,
  Edit,
  Trash2,
  Clock,
  Shield,
  Activity,
  Stethoscope,
  User,
  Phone,
  Mail,
  Navigation,
  Timer,
  RefreshCw,
  CheckCircle,
  XCircle,
  Map,
  MapPin,
  ExternalLink,
  Megaphone,
  AtSign,
  Award,
  Home,
  ClipboardList,
  UserCog,
  Users,
  ChevronUp,
  PanelLeft,
  CircleUser,
  Loader2,
  ArrowLeft,
  ArrowRight,
} from "lucide-react"

export const Icons = {
  AlertTriangle,
  Building2,
  Plus,
  MessageSquare,
  Bell,
  Send,
  UserCheck,
  Tag,
  Calendar,
  Eye,
  Edit,
  Trash2,
  Clock,
  Shield,
  Activity,
  Stethoscope,
  User,
  Phone,
  Mail,
  Navigation,
  Timer,
  RefreshCw,
  CheckCircle,
  XCircle,
  Map,
  MapPin,
  ExternalLink,
  Megaphone,
  AtSign,
  Award,
  Home,
  ClipboardList,
  UserCog,
  Users,
  ChevronUp,
  PanelLeft,
  CircleUser,
  spinner: Loader2,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
}
