export const gujaratDistricts = [
  "Ahmedabad",
  "Amreli",
  "Anand",
  "Aravalli",
  "Banaskantha (Palanpur)",
  "Bharuch",
  "Bhavnagar",
  "Botad",
  "Chhota Udepur",
  "Dahod",
  "Dangs (Ahwa)",
  "Devbhoomi Dwarka",
  "Gandhinagar",
  "Gir Somnath",
  "Jamnagar",
  "Junagadh",
  "Kachchh",
  "Kheda (Nadiad)",
  "Mahisagar",
  "Mehsana",
  "Morbi",
  "Narmada (Rajpipla)",
  "Navsari",
  "Panchmahal (Godhra)",
  "Patan",
  "Porbandar",
  "Rajkot",
  "Sabarkantha (Himmatnagar)",
  "Surat",
  "Surendranagar",
  "Tapi (Vyara)",
  "Vadodara",
  "Valsad",
]

export const gujaratData: Record<string, string[]> = {
  Ahmedabad: [
    "Ahmedabad",
    "Bavla",
    "Daskroi",
    "Detroj-Rampura",
    "Dhandhuka",
    "Dholera",
    "Dholka",
    "Mandal",
    "Sanand",
    "Viramgam",
  ],
  Amreli: [
    "Amreli",
    "Babra",
    "Bagasara",
    "Dhari",
    "Jafrabad",
    "Khambha",
    "Kunkavav Vadia",
    "Lathi",
    "Lilia",
    "Rajula",
    "Savarkundla",
  ],
  Anand: ["Anand", "Anklav", "Borsad", "Khambhat", "Petlad", "Sojitra", "Tarapur", "Umreth"],
  Aravalli: ["Bayad", "Bhiloda", "Dhansura", "Malpur", "Meghraj", "Modasa"],
  "Banaskantha (Palanpur)": [
    "Amirgadh",
    "Deesa",
    "Dantiwada",
    "Kankrej",
    "Lakhani",
    "Palanpur",
    "Suigam",
    "Tharad",
    "Vadgam",
    "Vav",
  ],
  Bharuch: ["Amod", "Ankleshwar", "Bharuch", "Hansot", "Jambusar", "Jhagadia", "Netrang", "Vagra", "Valia"],
  Bhavnagar: ["Bhavnagar", "Gariadhar", "Ghogha", "Mahuva", "Palitana", "Sihor", "Talaja", "Umrala", "Vallabhipur"],
  Botad: ["Botad", "Gadhada", "Barwala", "Ranpur"],
  "Chhota Udepur": ["Chhota Udepur", "Devgadh Baria", "Kavant", "Nasvadi", "Sankheda"],
  Dahod: ["Dahod", "Garbada", "Jhalod", "Limkheda", "Sanjeli", "Ghodabh"],
  "Dangs (Ahwa)": ["Ahwa", "Bansda", "Waghai", "Subir"],
  "Devbhoomi Dwarka": ["Dwarka", "Khambhalia", "Okhamandal"],
  Gandhinagar: ["Gandhinagar", "Dehgam", "Kalol", "Mansa"],
  "Gir Somnath": ["Gir Gadhada", "Junagadh Rural", "Jamjodhpur", "Talala", "Una"],
  Jamnagar: ["Jamnagar", "Jodiya", "Kalavad", "Lalpur", "Malia"],
  Junagadh: ["Junagadh", "Bhesana", "Keshod", "Manavadar", "Mangrol", "Mendarda", "Vanthali", "Visavadar"],
  Kachchh: ["Anjar", "Bhuj", "Bhachau", "Lakhpat", "Mandvi", "Mundra", "Nakhatrana", "Rapar"],
  "Kheda (Nadiad)": ["Balasinor", "Kheda", "Matar", "Mehmedabad", "Nadiad", "Thasra", "Vaso"],
  Mahisagar: ["Lunawada", "Santrampur", "Virpur"],
  Mehsana: ["Becharaji", "Kadi", "Kheralu", "Mehsana", "Satlasana", "Unjha", "Vadnagar", "Vijapur", "Visnagar"],
  Morbi: ["Morbi", "Tankara", "Wankaner"],
  "Narmada (Rajpipla)": ["Nandod", "Sagbara", "Tilakwada"],
  Navsari: ["Chikhli", "Navsari", "Vansda"],
  "Panchmahal (Godhra)": ["Godhra", "Jambughoda", "Kalol", "Morwa", "Shehera"],
  Patan: ["Patan", "Sami", "Santalpur", "Sidhpur"],
  Porbandar: ["Porbandar", "Kutiyana", "Ranavav"],
  Rajkot: [
    "Dhoraji",
    "Gondal",
    "Jamkandorna",
    "Jasdan",
    "Jetpur",
    "Kotada Sangani",
    "Lodhika",
    "Paddhari",
    "Rajkot",
    "Upleta",
    "Vinchhiya",
  ],
  "Sabarkantha (Himmatnagar)": ["Himmatnagar", "Idar", "Khedbrahma", "Prantij", "Talod", "Vadali", "Vijaynagar"],
  Surat: ["Bardoli", "Choryasi", "Kamrej", "Mandvi", "Mangrol", "Olpad", "Umarpada", "Palsana"],
  Surendranagar: ["Limbdi", "Muli", "Sayla", "Thangadh", "Wadhwan"],
  "Tapi (Vyara)": ["Dolvan", "Kukarmunda", "Nizar", "Songadh", "Valod", "Vyara", "Uchhal"],
  Vadodara: ["Dabhoi", "Padra", "Savli", "Sinor", "Vadodara", "Vaghodia"],
  Valsad: ["Dharampur", "Kaparada", "Pardi", "Umbargaon", "Valsad", "Vapi"],
}
